CTPError:
  - 
    Code: 0
    Error: CTP-正确
  -
    Code: 1
    Error: CTP-不在已同步状态
  - 
    Code: 2
    Error: CTP-会话信息不一致
  -
    Code: 3
    Error: CTP-不合法的登录
  - 
    Code: 4
    Error: CTP-用户不活跃
  - 
    Code: 5
    Error: CTP-重复的登录
  - 
    Code: 6
    Error: CTP-还没有登录
  - 
    Code: 7
    Error: CTP-还没有初始化
  - 
    Code: 8
    Error: CTP-前置不活跃
  - 
    Code: 9
    Error: CTP-无此权限
  - 
    Code: 10
    Error: CTP-修改别人的口令
  - 
    Code: 11
    Error: CTP-找不到该用户
  - 
    Code: 12
    Error: CTP-找不到该经纪公司
  - 
    Code: 13
    Error: CTP-找不到投资者
  - 
    Code: 14
    Error: CTP-原口令不匹配
  - 
    Code: 15
    Error: CTP-报单字段有误
  - 
    Code: 16
    Error: CTP-找不到合约
  -
    Code: 17
    Error: CTP-合约不能交易
  - 
    Code: 18
    Error: CTP-经纪公司不是交易所的会员
  - 
    Code: 19
    Error: CTP-投资者不活跃
  - 
    Code: 20
    Error: CTP-投资者未在交易所开户
  - 
    Code: 21
    Error: CTP-该交易席位未连接到交易所
  - 
    Code: 22
    Error: CTP-报单错误：不允许重复报单
  - 
    Code: 23
    Error: CTP-错误的报单操作字段
  - 
    Code: 24
    Error: CTP-撤单已报送，不允许重复撤单
  -
    Code: 25
    Error: CTP-撤单找不到相应报单
  - 
    Code: 26
    Error: CTP-报单已全成交或已撤销，不能再撤
  - 
    Code: 27
    Error: CTP-不支持的功能
  - 
    Code: 28
    Error: CTP-没有报单交易权限
  -
    Code: 29
    Error: CTP-只能平仓
  - 
    Code: 30
    Error: CTP-平仓量超过持仓量
  - 
    Code: 31
    Error: CTP-资金不足
  -
    Code: 32
    Error: CTP-主键重复
  -
    Code: 33
    Error: CTP-找不到主键
  - 
    Code: 34
    Error: CTP-设置经纪公司不活跃状态失败
  - 
    Code: 35
    Error: CTP-经纪公司正在同步
  -
    Code: 36
    Error: CTP-经纪公司已同步
  -
    Code: 37
    Error: CTP-现货交易不能卖空
  - 
    Code: 38
    Error: CTP-不合法的结算引用
  - 
    Code: 39
    Error: CTP-交易所网络连接失败
  - 
    Code: 40
    Error: CTP-交易所未处理请求超过许可数
  - 
    Code: 41
    Error: CTP-交易所每秒发送请求数超过许可数
  - 
    Code: 42
    Error: CTP-结算结果未确认
  - 
    Code: 43
    Error: CTP-没有对应的入金记录
  - 
    Code: 44
    Error: CTP-交易所已经进入连续交易状态
  - 
    Code: 45
    Error: CTP-找不到预埋（撤单）单
  - 
    Code: 46
    Error: CTP-预埋（撤单）单已经发送
  - 
    Code: 47
    Error: CTP-预埋（撤单）单已经删除
  - 
    Code: 48
    Error: CTP-无效的投资者或者密码
  - 
    Code: 49
    Error: CTP-不合法的登录IP地址
  - 
    Code: 50
    Error: CTP-平今仓位不足
  - 
    Code: 51
    Error: CTP-平昨仓位不足
  - 
    Code: 52
    Error: CTP-经纪公司没有足够可用的条件单数量
  - 
    Code: 53
    Error: CTP-投资者没有足够可用的条件单数量
  - 
    Code: 54
    Error: CTP-经纪公司不支持条件单
  - 
    Code: 55
    Error: CTP-重发未知单经纪公司/投资者不匹配
  -
    Code: 56
    Error: CTP-同步动态令牌失败
  -
    Code: 57
    Error: CTP-动态令牌校验错误
  - 
    Code: 58
    Error: CTP-找不到动态令牌配置信息
  -
    Code: 59
    Error: CTP-不支持的动态令牌类型
  -
    Code: 60
    Error: CTP-用户在线会话超出上限
  -
    Code: 61
    Error: CTP-该交易所不支持套利/做市商类型报单
  -
    Code: 62
    Error: CTP-没有条件单交易权限
  -
    Code: 63
    Error: CTP-客户端认证失败
  - 
    Code: 64
    Error: CTP-客户端未认证
  -
    Code: 65
    Error: CTP-该合约不支持互换类型报单
  - 
    Code: 66
    Error: CTP-该期权合约只支持投机类型报单
  -
    Code: 67
    Error: CTP-执行宣告错误，不允许重复执行
  - 
    Code: 68
    Error: CTP-重发未知执行宣告经纪公司/投资者不匹配
  - 
    Code: 69
    Error: CTP-只有期权合约可执行
  -
    Code: 70
    Error: CTP-该期权合约不支持执行
  -
    Code: 71
    Error: CTP-执行宣告字段有误
  -
    Code: 72
    Error: CTP-执行宣告撤单已报送，不允许重复撤单
  -
    Code: 73
    Error: CTP-执行宣告撤单找不到相应执行宣告
  -
    Code: 74
    Error: CTP-执行仓位不足
  -
    Code: 75
    Error: CTP-连续登录失败次数超限，登录被禁止
  -
    Code: 76
    Error: CTP-非法银期代理关系
  - 
    Code: 77
    Error: CTP-无此功能
  -
    Code: 78
    Error: CTP-发送报单失败
  -
    Code: 79
    Error: CTP-发送报单操作失败
  -
    Code: 80
    Error: CTP-交易所不支持的价格类型
  -
    Code: 81
    Error: CTP-错误的执行类型
  -
    Code: 82
    Error: CTP-无效的组合合约
  -
    Code: 83
    Error: CTP-该合约不支持询价
  -
    Code: 84
    Error: CTP-重发未知报价经纪公司/投资者不匹配
  -
    Code: 85
    Error: CTP-该合约不支持报价
  -
    Code: 86
    Error: CTP-报价撤单找不到相应报价
  -
    Code: 87
    Error: CTP-该期权合约不支持放弃执行
  -
    Code: 88
    Error: CTP-该组合期权合约只支持IOC
  - Code: 89
    Error: CTP-打开文件失败
  -
    Code: 90
    Error: CTP：查询未就绪，请稍后重试
  -
    Code: 91
    Error: CTP：交易所返回的错误
  - 
    Code: 92
    Error: CTP-报价衍生单要等待交易所返回才能撤单
  - 
    Code: 93
    Error: CTP-找不到组合合约映射
  -
    Code: 94
    Error: CTP-不允许撤销OTC衍生报单
  -
    Code: 95
    Error: CTP：不支持的价格
  -
    Code: 101
    Error: CTP-用户在本系统没有报单权限
  - 
    Code: 102
    Error: CTP-系统缺少灾备标示号
  -
    Code: 103
    Error: CTP-该交易所不支持批量撤单
  -
    Code: 106
    Error: CTP-投资者限仓
  -
    Code: 113
    Error: CTP-当前时间禁止询价
  -
    Code: 114
    Error: CTP-当前价差禁止询价
  - 
    Code: 116
    Error: CTP-下单频率限制
  -
    Code: 131
    Error: CTP：您当前密码为弱密码，请修改成强密码后重新登录
  -
    Code: 139
    Error: CTP-当前时间禁止行权
  -
    Code: 140
    Error: CTP-首次登录必须修改密码，请修改密码后重新登录
  -
    Code: 141
    Error: CTP-您当前密码已过期，请修改后登录
  -
    Code: 142
    Error: CTP-修改密码失败。新密码不允许与旧密码相同
  -
    Code: 143
    Error: CTP-您登录失败次数过多，IP被禁止登入CTP
  -
    Code: 144
    Error: CTP-您当前IP在黑名单中，被禁止登入CTP
  -
    Code: 145
    Error: CTP-终端在本系统没有认证权限
  -
    Code: 146
    Error: CTP-缺少InvestorID字段，请填入InvestorID
  -
    Code: 147
    Error: CTP-缺少ExchangeID字段，请填入ExchangeID
  -
    Code: 148
    Error: CTP-无效的ExchangeID字段，请填入正确的ExchangeID
  -
    Code: 149
    Error: CTP-缺少AccountID字段，请填入AccountID
  -
    Code: 150
    Error: CTP-交易所代码错误
  -
    Code: 151
    Error: CTP-删除拆分组合指令：没有找到该记录
  -
    Code: 152
    Error: CTP-删除拆分组合指令：原指令需要等待30s 才能删除
  -
    Code: 153
    Error: CTP-拆分组合钱不足
  -
    Code: 154
    Error: CTP-查询核心忙 请稍后重试
  -
    Code: 1000
    Error: CTP-银期转账：发送机构代码错误
  -
    Code: 1001
    Error: CTP-银期转账：取平台流水号错误
  -
    Code: 1002
    Error: CTP-银期转账：不合法的转账银行
  - 
    Code: 1003
    Error: CTP-银期转账：已经开户
  -
    Code: 1004
    Error: CTP-银期转账：未开户
  -
    Code: 1005
    Error: CTP-银期转账：处理中
  -
    Code: 1006
    Error: CTP-银期转账：交易超时
  -
    Code: 1007
    Error: CTP-银期转账：找不到记录
  -
    Code: 1008
    Error: CTP-银期转账：找不到被冲正的原始交易
  -
    Code: 1009
    Error: CTP-银期转账：连接主机失败
  - 
    Code: 1010
    Error: CTP-银期转账：发送失败
  - 
    Code: 1011
    Error: CTP-银期转账：迟到应答
  -
    Code: 1012
    Error: CTP-银期转账：冲正交易银行代码错误
  -
    Code: 1013
    Error: CTP-银期转账：冲正交易银行账户错误
  -
    Code: 1014
    Error: CTP-银期转账：冲正交易经纪公司代码错误
  -
    Code: 1015
    Error: CTP-银期转账：冲正交易资金账户错误
  -
    Code: 1016
    Error: CTP-银期转账：冲正交易交易金额错误
  -
    Code: 1017
    Error: CTP-银期转账：数据库操作错误
  -
    Code: 1018
    Error: CTP-银期转账：发送到交易系统失败
  -
    Code: 1019
    Error: CTP-银期转账：没有签到
  -
    Code: 1020
    Error: CTP-银期转账：已经签到
  -
    Code: 1021
    Error: CTP-银期转账：金额或次数超限
  -
    Code: 1022
    Error: CTP-银期转账：这一时间段不能转账
  -
    Code: 1023
    Error: 银行主机错
  -
    Code: 1024
    Error: CTP-银期转账：银行已经冲正
  -
    Code: 1025
    Error: CTP-银期转账：银行流水不存在
  -
    Code: 1026
    Error: CTP-银期转账：机构没有签约
  -
    Code: 1027
    Error: CTP-银期转账：存在转账，不能销户
  -
    Code: 1028
    Error: CTP-银期转账：银行不支持冲正
  -
    Code: 1029
    Error: CTP-银期转账：重复的银行流水
  - 
    Code: 1030
    Error: CTP-银期转账：转账系统忙，稍后再试
  -
    Code: 1031
    Error: CTP-银期转账：MAC密钥正在同步
  -
    Code: 1032
    Error: CTP-银期转账：资金账户已经登记
  -
    Code: 1033
    Error: CTP-银期转账：银行账户已经登记
  -
    Code: 1034
    Error: CTP-银期转账：重复的银行流水,重发成功
  -
    Code: 1035
    Error: CTP-银期转账：该币种代码不支持
  -
    Code: 1036
    Error: CTP-银期转账：MAC值验证失败
  -
    Code: 1037
    Error: CTP-银期转账：不支持银行端发起的二级代理商转账和查询
  -
    Code: 1038
    Error: CTP-银期转账：PIN密钥正在同步
  -
    Code: 1039
    Error: CTP-银期转账：建行发起的二级代理商查询
  - 
    Code: 1040
    Error: CTP-银期转账：银行账户不能为空
  -
    Code: 1041
    Error: CTP-银期转账：资金账户存在，预约开户失败
  -
    Code: 1042
    Error: CTP-银期转账：开户请求的银行卡号和预留的账号不同
  -
    Code: 1043
    Error: 银行系统内部错误
  -
    Code: 2000
    Error: CTP-该报盘未连接到银行
  -
    Code: 2001
    Error: CTP-资金密码错误
  -
    Code: 2004
    Error: CTP-银行流水号重复
  -
    Code: 2005
    Error: CTP-报盘流水号重复
  -
    Code: 2006
    Error: CTP-被冲正流水不存在(冲正交易)
  -
    Code: 2007
    Error: CTP-原流水已冲正(冲正交易)
  -
    Code: 2008
    Error: CTP-与原流水信息不符(冲正交易)
  -
    Code: 2009
    Error: CTP-证件号码或类型错误
  -
    Code: 2011
    Error: CTP-资金账户不存在
  -
    Code: 2012
    Error: CTP-资金账户已经销户
  -
    Code: 2013
    Error: CTP-该交易不能执行手工冲正
  -
    Code: 2014
    Error: CTP-转帐金额错误
  -
    Code: 2015
    Error: CTP-找不到汇率
  -
    Code: 2016
    Error: CTP-找不到预约开户请求
  -
    Code: 2017
    Error: CTP-重复的预约开户请求
  -
    Code: 999999
    Error: CTP-等待银期报盘处理结果
  -
    Code: 2050
    Error: 建行银期：密码与认证(业务错误)
  -
    Code: 2051
    Error: 建行银期：数量与限额(业务错误)
  -
    Code: 2052
    Error: 建行银期：权限控制(业务错误)
  -
    Code: 2053
    Error: 建行银期：信息滥缺(业务错误)或者数据内容相关(技术错误)
  -
    Code: 2054
    Error: 建行银期：内容非法(业务错误)
  -
    Code: 2055
    Error: 建行银期：重复交易(业务错误)
  -
    Code: 2056
    Error: 建行银期： 时间与期限(业务错误)
  -
    Code: 2057
    Error: 建行银期：风险控制(业务错误)
  -
    Code: 2058
    Error: 建行银期：业务逻辑(业务错误)
  -
    Code: 2059
    Error: 建行银期： 不确定交易结果(技术错误)
  -
    Code: 2060
    Error: 建行银期： 硬件错误(技术错误)
  -
    Code: 2062
    Error: 建行银期： 读写相关(技术错误)
  -
    Code: 2063
    Error: 建行银期： 数据库相关(技术错误)
  -
    Code: 2064
    Error: 建行银期：网络通讯(技术错误)
  -
    Code: 2065
    Error: 建行银期：安全服务(技术错误)
  -
    Code: 2066
    Error: 建行银期： 组件模块(技术错误)
  -
    Code: 2067
    Error: 建行银期：流量控制(技术错误)
  -
    Code: 2069
    Error: 建行银期：技术逻辑(技术错误)
  -
    Code: 2070
    Error: 建行银期：纯技术性错误(技术错误)
  -
    Code: 3001
    Error: CTP-银期换汇：取平台流水号错误
  -
    Code: 3002
    Error: CTP-银期换汇：不合法的转账银行
  -
    Code: 3006
    Error: CTP-银期换汇：处理中
  -
    Code: 3006
    Error: CTP-银期换汇：交易超时
  -
    Code: 3007
    Error: CTP-银期换汇：找不到记录
  -
    Code: 3009
    Error: CTP-银期换汇：连接主机失败
  -
    Code: 3010
    Error: CTP-银期换汇：发送失败
  -
    Code: 3011
    Error: CTP-银期换汇：迟到应答
  -
    Code: 3017
    Error: CTP-银期换汇：数据库操作错误
  -
    Code: 3019
    Error: CTP-银期换汇：没有签到
  -
    Code: 3020
    Error: CTP-银期换汇：已经签到
  -
    Code: 3021
    Error: CTP-银期换汇：金额或次数超限
  -
    Code: 3022
    Error: CTP-银期换汇：这一时间段不能换汇
  -
    Code: 3023
    Error: CTP-银期换汇：银行主机错
  -
    Code: 3026
    Error: CTP-银期换汇：机构没有签约
  -
    Code: 3030
    Error: CTP-银期换汇：换汇系统忙，稍后再试
  -
    Code: 3035
    Error: CTP-银期换汇：该币种代码不支持
  -
    Code: 3036
    Error: CTP-银期换汇：银行帐号不正确
  -
    Code: 3037
    Error: CTP-银期换汇：银行帐户余额不足
  -
    Code: 3038
    Error: CTP-银期换汇：凭证号重复
  -
    Code: 3039
    Error: CTP-不支持该API版本
  -
    Code: 3040
    Error: CTP-无效的API KEY
  -
    Code: 3041
    Error: CTP-期权对冲,履约对冲:非期权合约
  -
    Code: 3042
    Error: CTP-期权对冲,履约对冲:请求引用不合法
  -
    Code: 3043
    Error: CTP-期权对冲,履约对冲:非法字段
  -
    Code: 3044
    Error: CTP-期权对冲,履约对冲:撤销未找到记录
  -
    Code: 3045
    Error: CTP-期权对冲,履约对冲:对冲状态不对，不能撤销
  -
    Code: 3046
    Error: CTP-期权对冲,履约对冲:不能重复设置，只能先撤销再设置
  -
    Code: 3047
    Error: CTP-报价不支持改投机套保类型
  -
    Code: 4040
    Error: CTP-API Front shake hand err
  -
    Code: 4041
    Error: CTP-DUPLICATE_SUBMIT
  -
    Code: 4042
    Error: CTP-IP授权验证失败
  -
    Code: 4043
    Error: CTP-用户与客户端授权验证失败
  -
    Code: 4097
    Error: CTP-网络读失败
  -
    Code: 4098
    Error: CTP-网络写失败
  -
    Code: 8193
    Error: CTP-接收心跳超时
  -
    Code: 8194
    Error: CTP-发送心跳失败
  -
    Code: 8195
    Error: CTP-收到错误报文
