
REMError:
  -
    Code: 0
    Error: successed
  - 
    Code: 1
    Error: 连接服务失败
  -
    Code: 2
    Error: 远程服务器断开，连接服务失败
  - 
    Code: 3
    Error: 本地网络断开
  - 
    Code: 4
    Error: 网络异常
  - 
    Code: 5
    Error: 登录服务失败
  - 
    Code: 6
    Error: 用户未登录
  -
    Code: 7
    Error: 未连接服务器
  -
    Code: 8
    Error: 错误的交易对象句柄
  - 
    Code: 9
    Error: 设置订单 token 错误
  - 
    Code: 10
    Error: 密码错误
  - 
    Code: 11
    Error: 订单数量错误，必须在1-4之间
  - 
    Code: 12
    Error: 合约类型错误，只支持2-期权以及3-期货
  - 
    Code: 13
    Error: 期权合约代码错误，无法解析的期权合约代码，形式必须为m1703-C-2250
  -
    Code: 14
    Error: 合约代码错误，超出交易合约代码限制
  -
    Code: 15
    Error: 流控限制
  - 
    Code: 16
    Error: 流控参数修改超出允许范围
